## YAML Template.
---
datasource:
  default: ${APP_ENV}
  development:
    username: ""
    password: ""
    url: "jdbc:h2:./page_analyzer"
  production:
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    url: ${JDBC_DATABASE_URL}

ebean:
  ddl:
    run: true
    generate: true
    seedSql: seed.sql

#ebean:
#  migration:
#    run: true
